### PR TITLE
Update Helper.php

### PR DESCRIPTION
**Pull request by xchs**
Fix the feed share directory.

### CODE REVIEW

**Comment by psi-4ward** [comment]
pls test, I'll tag a new version on success.
thanks :)

**Comment by sizta** [comment]
Yes, mission accomplished.
xml file was successfully generated and updated in web/share/
Tested with Contao 4.4.32

**Comment by fritzmg** [comment]
This breaks compatibility with Contao 3. The method `\Contao\StringUtil::stripRootDir` is not available there.

**Comment by psi-4ward** [comment]
Thats really bad! Can anyone fix this please?

**Comment by fritzmg** [comment]
May be just do
```php
if (class_exists(\Contao\CoreBundle\ContaoCoreBundle::class)) {
    $objRss = new \File(StringUtil::stripRootDir(System::getContainer()->getParameter('contao.web_dir')) . '/share/' . $strFile . '.xml');
} else {
    $objRss = new \File($strFile . '.xml');
}
```

**Comment by psi-4ward** [comment]
Yes smth like that. Can you prep a PR?

**Comment by fritzmg** [comment]
Only an untested one, since I am not actively using this extension ;). The problem came up in a community forum thread.

**Comment by psi-4ward** [comment]
Probably someone there could test the fix?

**Pull request merged**
